# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# example:
# https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml

version: 2
updates:
  # `package-ecosystem` more configurations: https://docs.github.com/zh/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    open-pull-requests-limit: 10
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # - package-ecosystem: "gomod"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #     time: "02:00"
  #   open-pull-requests-limit: 10
  #   groups:
  #     patch-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "patch"
  #     minor-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"

  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #     time: "02:00"
  #   open-pull-requests-limit: 10
  #   groups:
  #     patch-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "patch"
  #     minor-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"

  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #     time: "02:00"
  #   open-pull-requests-limit: 10
  #   groups:
  #     patch-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "patch"
  #     minor-updates:
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"
